# SETUP -----------------------------------------------------------------------------------------------------------------------

#Requires R 4.1.3 and Rtools 4.0
#dplyr 1.1.2; httr 1.4.7;jsonlite 1.8.4; BiocManager 1.30.22; rWikiPathways 1.14.0; RCy3 2.14.2
#Cytoscape 3.10.1

setwd("~/GitHub/SCZ-CNV")

packages <- c("dplyr","httr","jsonlite","stringr","gProfileR")
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}
if(!"rWikiPathways" %in% installed.packages()){
  if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
  BiocManager::install("rWikiPathways")
}
if(!"RCy3" %in% installed.packages()){
  if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
  BiocManager::install("RCy3")
}
  #Checking if required packages are installed and installing if not
  #Different structure for rWikiPathways and RCy3 packages as these are not installed directly but via the BiocManager package
invisible(lapply(c(packages,"rWikiPathways","RCy3"), require, character.only = TRUE))
  #Loading libraries

sysdatetime <- Sys.time()
datetime <- format(sysdatetime, format = "%d-%m-%Y_%Hh%M")
dir.create("Outputs")
dir.create(sprintf("Outputs/Session-%s",datetime))
dir.create(sprintf("Outputs/Session-%s/Networks",datetime))
  #Creating directories for outputs generated by this script to be saved in; new "Session" folder created each time the script is ran (contains generated networks, metadata, and sessionInfo)
nw_savepath <- sprintf("%1$s/Outputs/Session-%2$s/Networks/",getwd(),datetime)
file.create(sprintf("Outputs/Session-%s/metadata.txt",datetime))
  #Creating a new metadata file with the current date and time as suffix for easier organisation
  #Such a metadata file should be generated every time this script is ran to record parameters and versions of functions or databases, including the time avoids files being overwritten if the script is run multiple times a day (can even include seconds if script is ran multiple times per minute)
metadata.add <- function(info) {
  write(sapply(info, as.character), sprintf("Outputs/Session-%s/metadata.txt",datetime),append=TRUE, sep = "\n")
}
metadata.add(sysdatetime)
metadata.add(Sys.timezone())
metadata.add("")
  #Adding the timezone, date, and time to the metadata 

invisible(file.create(sprintf("Outputs/Session-%s/sessioninfo-%s.txt",datetime,datetime)))
writeLines(capture.output(sessionInfo()),sprintf("Outputs/Session-%s/sessioninfo-%s.txt",datetime,datetime))
  #Generating and adding a sessionInfo file to the current session output folder

cytoscapePing()
cytoscapeVersionInfo()
  #Checking if Cytoscape is running and version info
metadata.add(capture.output(cytoscapeVersionInfo()))

checkinstall.app <- function(app) {
  status_string <- getAppStatus(app)
    #Getting install status of app
  words <- strsplit(status_string, " ")[[1]]
  last_word <- tail(words, 1)
    #getAppStatus returns a character string instead of a logical value, so the last word (usually either "Installed" or "Uninstalled") from the output is checked
  if (last_word == "Installed") {
    print(sprintf("App %s is already installed.",app))
    } else {
    installApp(app)
    print(sprintf("Installed app %s.",app))
    }
}
  #Function to check whether required Cytoscape apps are installed and installing them if not
applist <- c("Wikipathways", "DisGeNET-app", "CyTargetLinker","stringApp","BridgeDb","clusterMaker2")
  #WikiPathways v.3.3.10
  #DisGeNET-app v.7.3.0
  #CyTargetLinker v. 4.1.0
  #stringApp v. 2.0.1
  #BridgeDb v.1.2.0
  #clusterMaker2 v.2.3.4
lapply(applist,checkinstall.app)
  #Checking and installing (if required) necessary Cytoscape apps
lapply(applist,getAppInformation)
metadata.add("Required Cytoscape apps and versions:")
invisible(metadata.add(print(lapply(applist,getAppInformation))))
metadata.add("")

# FUNCTION DICTIONARY-------------------------------------------------------------------------------------------------------------------
queryspecies.wp <- c("Homo sapiens","Rattus norvegicus","Mus musculus")
getPathways.wp <- function(i) {
  pw <- findPathwaysByText(i)
  pw <- pw %>%
    dplyr::filter(species %in% queryspecies.wp)
    #Filtering by species
  pw.ids <- paste0(i, "_wpids")
  assign(pw.ids, as.character(pw$id),envir = .GlobalEnv)
    #Extracting WP IDs
}
  #Function to query WikiPathways using keyword and to extract WP IDs for the import function

createNodeSource <- function(source,doi=NULL) {
  if (source == "WikiPathways") {
  networkname <- getNetworkName()
  nodetable <- paste0(networkname," default  node") 
  } 
    #Networks imported from WikiPathways have a type in the node table designations, as they have 2 spaces between "default" and "node" instead of one
    #This check determines which node table name format is to be applied depending on the source (WikiPathways or other)
  else {
    networkname <- getNetworkName()
    nodetable <- paste0(networkname," default node") 
    }
  commandsRun(sprintf("table create column columnName=WikiPathways table=%s type=string",nodetable))
  commandsRun(sprintf("table create column columnName=DisGeNET table=%s type=string",nodetable))
  commandsRun(sprintf("table create column columnName=PharmGKB table=%s type=string",nodetable))
  commandsRun(sprintf("table create column columnName=Literature table=%s type=string",nodetable))
  commandsRun(sprintf("table create column columnName=Literature.doi table=%s type=string",nodetable))
    #Creating a new column for each source used for all networks
  commandsRun(sprintf("table set values columnName=%1$s handleEquations=false rowList=all table=%2$s value=1",source,nodetable))
    #Filling the new column of the corresponding source with 1 to indicate which source the node is imported from 
  if (!is.null(doi)) {
  commandsRun(sprintf("table set values columnName=Literature.doi handleEquations=false rowList=all table=%1$s value=%2$s",nodetable,doi))
    #Adding doi for literature used if provided
  }
}
  #Function to create new column in node table specifying origin of network/node

import <- function(j) {
  commandsRun(paste0('wikipathways import-as-network id=', j))
    #Pasting WikiPathways IDs into a Cytoscape command line prompt to import as networks
  createNodeSource("WikiPathways")
    #Filling the 'WikiPathways' column with 1 to indicate the source
}
  #Importing pathways from WikiPathways by pathway ID

disgenetRestUrl<-function(netType,host="127.0.0.1",port=1234,version="v7"){
  if(is.null(netType)){
    print("Network type not specified.")
  }else{
    disgeneturl<-sprintf("http://%s:%i/disgenet/%s/%s",host,port,version,netType)
  }
  return (disgeneturl)
}
net <- "gene-disease-net"
disgenetRestUrl(netType = net)
  #Defining object for REST to call DisGeNET automation module; defining that we will be using gene-disease associations (GDA)
disgenetRestCall<-function(netType,netParams){
  disgeneturl<-disgenetRestUrl(netType)
  restCall<-POST(disgeneturl, body = netParams, encode = "json")
  result<-content(restCall,"parsed")
  return(result)
}
  #Object that executes REST calls to DisGeNET module in Cytoscape 
geneDisParams <- function(source,dis,min) {list(
  source = source,
  assocType = "Any",
  diseaseClass = "Any",
  diseaseSearch = dis,
  geneSearch = " ",
  initialScoreValue = min,
  finalScoreValue = "1.0"
)}
  #Specifying parameters of the GDA network to be imported


# SCHIZOPHRENIA =======================================================================================================================
## IMPORTING AND MERGING ---------------------------------------------------------------------------------------------------------------

genedisparams.scz.df <- read.table("CSVs/disgenetparams-scz.txt",header=TRUE,sep = "\t")
  #Loading relevant gene-disease networks from DisGeNET
  #Networks of interest manually added into tsv where it is easier to adjust filters
disgeneturl <- c()
  #Preparing container for DisGeNET URL to be saved for addition to metadata file
apply(genedisparams.scz.df,1,function(row) {
  gdp <- geneDisParams(row["source"],row["dis"],row["min"])
  disgeneturl <<- disgenetRestUrl(net)
    #Fetching the DisGeNET URL used to make this call 
  geneDisResult <- disgenetRestCall(net,gdp)
    #Executing the DisGeNET query
  createNodeSource("DisGeNET")
    #Adding information about data source to each node
  mapTableColumn("geneName","Human","HGNC","Ensembl")
    #Mapping the HGNC gene name from the geneName column in the node table to Ensembl identifiers
  mapTableColumn("geneName","Human","Entrez Gene","Ensembl")
    #Mapping Entrez Gene IDs to Ensembl IDs
})  
  #Importing networks from DisGeNET

metadata.add(paste("DisGeNET URL:",disgeneturl))
metadata.add(paste("DisGeNET net type:",net))
metadata.add("")
  #Adding the DisGeNET URL and net type used to add networks to the metadata file


wpids <- c("4875","5412","4222","4942","5408","5402","5346","5405","5406","5407","4940","4905","5398","5399","4906","4657","4932")
sczcnv <- sapply(wpids, function(k) paste0("WP",k))
  #Manually adding relevant SCZ CNV pathways from WikiPathways

keyword.wp <- "Schizophrenia"
getPathways.wp(keyword.wp)
lapply(c(Schizophrenia_wpids,sczcnv), import)
  #Importing WP pathways (both manually added and by keyword). Also adds "WikiPathways" as NodeSource column to node table
metadata.add(paste("WikiPathways keywords:",keyword.wp))
metadata.add(paste("WikiPathways manually by ID:",paste(wpids,collapse =", ")))
metadata.add(paste("WikiPathways queried species:",paste(queryspecies.wp,collapse = ", ")))
  #Adding the keyword and species used to filter the WikiPathways query to the metadata file
metadata.add("")

commandsRun(sprintf("network import file columnTypeList='sa,sa,source,sa,sa,sa,sa' file=%s firstRowAsColumnNames=true rootNetworkList=-- Create new network collection -- startLoadRow=1", paste0(getwd(),"/CSVs/scz2022-Extended-Data-Table1.txt")))
  #Importing network from file
  #List of 120 genes implicated in Trubetskoy et al., doi: 10.1038/s41586-022-04434-5
commandsRun("table rename column columnName=Ensembl.ID newColumnName=Ensembl table=scz2022-Extended-Data-Table1.txt default node")
  #Renaming the Ensembl.ID column from the dataset to Ensembl for coherence with networks from other sources
createNodeSource("Literature","10.1038/s41586-022-04434-5")
  #Adding literature as  source to all imported nodes and adding the doi of the corresponding paper
renameNetwork("Trubetskoy risk genes")
  #Renaming the newly imported network
metadata.add("Literature")
metadata.add("Trubetskoy et al. doi: 10.1038/s41586-022-04434-5")


networklist.dup <- getNetworkList()
dup.filter <- function(input,suffix) {
  filtered_list <- input[substr(input, nchar(input) - 1,nchar(input))==suffix]
}
duplicates <- dup.filter(networklist.dup,"_1")
  #Getting duplicate networks (Cytoscape marks duplicate networks with a "_1" suffix to the network name)
delete.dupes <- function(nw) {
  setCurrentNetwork(nw)
  deleteNetwork()
}
lapply(duplicates,delete.dupes)
  #Selecting and deleting duplicate networks

networklist <- getNetworkList()
setCurrentNetwork(networklist[[1]])
for(i in 1:length(networklist)) {
  current <- getNetworkName()
  mergeNetworks(c(current,networklist[[i]]), paste(current,networklist[[i]]),"union",inNetworkMerge = TRUE,nodeKeys=c("Ensembl","Ensembl"))
}
  #Looping through the network list to merge all currently open networks with each other, creating one large unified network
renameNetwork("Schizophrenia supernetwork")
networklist <- getNetworkList()
snw_scz <- getNetworkName()
  #Getting the name of the unified network to preserve it from deletion
lapply(networklist[networklist != snw_scz],deleteNetwork)
  #Deleting all networks besides newly generated unified network
exportNetwork(filename=paste0(nw_savepath,paste(snw_scz,datetime, sep = " - ")),"CX", network = snw_scz, overwriteFile=FALSE)
  #Exporting the supernetwork as cx file and tagging it with the time and date made to match with metadata file

## FILTERING NETWORK ------------------------------------------------------------------------------------------------------------------
createColumnFilter(filter.name="type.label",column="Type","Label","IS")
createColumnFilter(filter.name="type.anchor",column="Type","Anchor","IS")
createColumnFilter(filter.name="type.group",column="Type","Group","IS")
createColumnFilter(filter.name="disease.name",column="diseaseName","Schizophrenia","IS")
createCompositeFilter(filter.name="type.label.anchor.group",c("type.label","type.anchor","type.group","disease.name"),"ANY")
deleteSelectedNodes()
  #Creating filters and deleting columns in the node table that are not relevant to the supernetwork (leftovers from import sources)
renameNetwork("Schizophrenia supernetwork - filtered")
snw_scz_filtered <- getNetworkName()
exportNetwork(filename=paste0(nw_savepath,paste(snw_scz_filtered,datetime, sep = " - ")),"CX", network = snw_scz_filtered, overwriteFile=FALSE)
  #Exporting the filtered supernetwork as cx file and tagging it with the time and date made to match with metadata file

## STRING --------------------------------------------------------------------------------------------------------------------------
commandsRun('string stringify colDisplayName=name column=Ensembl compoundQuery=true cutoff=0.9 includeNotMapped=true  networkType="full STRING network" species="Homo sapiens" networkNoGui=current')
commandsRun('string expand additionalNodes=100 network=current nodeTypes="Homo sapiens" selectivityAlpha=0.9')
  #STRINGifying and expanding the network with a 0.9 confidence cutoff (curated information)
mapTableColumn("stringdb::canonical name","Human","Uniprot-TrEMBL","Ensembl")
  #Mapping stringdb canonical names (Uniprot-TrEMBL identifiers) to Ensembl gene identifiers
  #This step generates a second Ensembl column ('Ensembl (1)') with ENSG identifiers for the STRING-imported nodes
renameTableColumn("Ensembl (1)","Ensembldup")
  #Renaming the duplicate Ensembl column for easier handling
mapTableColumn("Ensembl","Human","Ensembl","HGNC")
  #Generating a new column 'HGNC' from Ensembl identifiers - easier and less error-prone than merging various name columns from different import sources
renameTableColumn("HGNC","Name2")
  #Renaming the new 'HGNC' column to 'Name2', which is now to be used as default name column. ('shared name' and 'name' columns are immutable and cannot be deleted or renamed)
snw_scz_filtered_string <- getNetworkName()
exportNetwork(filename=paste0(nw_savepath,paste(snw_scz_filtered_string,datetime,sep= " - ")),"CX",network=snw_scz_filtered_string,overwriteFile=FALSE)
  #Exporting the filtered, stringified supernetwork as cx file and tagging it with the time and data to match with the metadata file

## CLUSTERING ----------------------------------------------------------------------------------------------------------------------
commandsRun('cluster glay clusterAttribute=__glayCluster createGroups=false network=current restoreEdges=true showUI=true undirectedEdges=true')
  #Clustering the network using the GLay community cluster from the clusterMaker Cytoscape app
snw_scz_filtered_string_clustered <- getNetworkName()
clustered_nodetable <- paste0(nw_savepath,sprintf("/%s node table.csv",snw_scz_filtered_string_clustered))
  #Saving the file path to the node table for easier reading during gene ontology analysis
renameTableColumn('__glayCluster','gLayCluster')
  #Renaming the newly generated gLayCluster column as the original name with two underscores is not recognized during gene ontology
commandsRun(sprintf('table export options=CSV outputFile=%1$s table="%2$s default  node"',clustered_nodetable,snw_scz_filtered_string_clustered))
  #Exporting the node table as .csv file to the current session's "Network" folder (note again the double space between 'node' and 'table' in the table name)
  #The node table contains the GLay cluster number for every node which is then used as reference for gene ontology tools
gene_cluster <- read.csv(clustered_nodetable)
gene_cluster$Ensembl <- ifelse(gene_cluster$Ensembl == gene_cluster$Ensembldup, as.character(gene_cluster$Ensembl),
                               ifelse(is.na(gene_cluster$Ensembl) | gene_cluster$Ensembl =="",as.character(gene_cluster$Ensembldup),
                                      ifelse(is.na(gene_cluster$Ensembldup) | gene_cluster$Ensembldup=="",as.character(gene_cluster$Ensembl),"No Match")))
  #As the identifier mapping from STRING ENSP to ENSG identifiers generates a second Ensembl column, they are merged into the originial Ensembl column if the contents of the cell match or either is blank
gene_cluster = subset(gene_cluster,select= -Ensembldup)
  #Removing the duplicate Ensembl column from the table
write.csv(gene_cluster, file=clustered_nodetable)
  #Overwriting the previously exported table with the version containing the merged Ensembl column
loadTableData(gene_cluster,data.key.column = "Ensembl",table.key.column = "Ensembl")
exportNetwork(filename=paste0(nw_savepath,paste(snw_scz_filtered_string_clustered,datetime,sep= " - ")),"CX",network=snw_scz_filtered_string_clustered,overwriteFile=FALSE)
  #Exporting the filtered, stringified, clustered supernetwork as cx file and tagging it with the time and data to match with the metadata file

## GENE ONTOLOGY ANALYSIS -----------------------------------------------------------------------------------------------------------
gene_cluster %>% select(c('gLayCluster','Ensembl'))
  #Reading the node table exported earlier for processing with gprofiler and selecting relevant columns
split_df <- split(gene_cluster$Ensembl,gene_cluster$gLayCluster)
split_list <- lapply(split_df, as.vector)
cluster1 <- split_list[[1]]
gprofiler()

## CTL EXTENSION ----------------------------------------------------------------------------------------------------------------------
hsa <- file.path(getwd(), "Linksets", "wikipathways-20220511-hsa-WP.xgmml")
hsa_react <- file.path(getwd(), "Linksets", "wikipathways-20220511-hsa-REACTOME.xgmml")
  #Loading the WikiPathways linksets available at https://cytargetlinker.github.io/pages/linksets/wikipathways
CTLextend.cmd = paste('cytargetlinker extend idAttribute="Ensembl" linkSetFiles="', hsa, ',', hsa_react, '" network=current direction=TARGETS', sep="")
  #Extending the network using the previously loaded linksets
commandsRun(CTLextend.cmd)
  #Extending the network with previously loaded linksets
layoutNetwork()
  #Adding basic network layout
snw_scz_ext <- getNetworkName()
exportNetwork(filename=paste0(nw_savepath,paste(snw_scz_ext,datetime, sep = " - ")),"CX", network = snw_scz_ext, overwriteFile=FALSE)
  #Exporting the CTL extended supernetwork as cx file and tagging it with the time and date made to match with metadata file
metadata.add("CyTargetLinker linksets: wikipathways-20220511-hsa-WP.xgmml, wikipathways-20220511-hsa-REACTOME.xgmml")
  #Adding information about the CTL extension to the metadata file

## SAVING ------------------------------------------------------------------------------------------------------------------------------

preserve <- c(snw_scz, snw_scz_ext)

# ADDICTION ===========================================================================================================================
## IMPORTING AND MERGING --------------------------------------------------------------------------------------------------------------
genedisparams.adc.df <- read.table("CSVs/disgenetparams-adc.txt",header=TRUE,sep = "\t")
  #Loading relevant gene-disease networks from DisGeNET
  #Networks of interest manually added into tsv where it is easier to adjust filters
apply(genedisparams.adc.df,1,function(row) {
  gdp <- geneDisParams(row["source"],row["dis"],row["min"])
  geneDisResult <- disgenetRestCall("gene-disease-net",gdp)
  createNodeSource("DisGeNET")
  mapToEnsembl("geneName","HGNC")
})

getPathways.wp("Dopamine")
getPathways.wp("Addiction")
lapply(c(Dopamine_wpids,Addiction_wpids), import)

networklist.dup <- getNetworkList()
dup.filter <- function(input,suffix) {
  filtered_list <- input[substr(input, nchar(input) - 1,nchar(input))==suffix]
}
duplicates <- dup.filter(networklist.dup,"_1")
  #Getting duplicate networks (Cytoscape marks duplicate networks with a "_1" suffix to the network name)
delete.dupes <- function(nw) {
  setCurrentNetwork(nw)
  deleteNetwork()
}
lapply(duplicates,delete.dupes)
  #Selecting and deleting duplicate networks

networklist <- getNetworkList()
networklist <- networklist[!networklist %in% preserve]
  #Getting all networks besides the big SCZ networks
setCurrentNetwork(networklist[[1]])
for(i in 1:length(networklist)) tryCatch({
  current <- getNetworkName()
  mergeNetworks(c(current,networklist[[i]]), paste(current,networklist[[i]]),"union",inNetworkMerge = TRUE,nodeKeys=c("Ensembl","Ensembl"))
}, error = function(e) {
  cat("An error occured:\n")
  cat("Error message: ", conditionMessage(e),"\n")
  cat("Call stack:\n")
  print(sys.calls())
})
#Looping through the network list to merge all currently open networks with each other, creating one large unified network

renameNetwork("Addiction supernetwork")
networklist <- getNetworkList()
snw_adc <- getNetworkName()
  #Getting the name of the unified network to preserve it from deletion
lapply(networklist[networklist != snw_adc ],deleteNetwork)
  #Deleting all networks besides newly generated unified networks

## CTL EXTENSION -----------------------------------------------------------------------------------------------------------------------

hsa <- file.path(getwd(), "Linksets", "wikipathways-20220511-hsa-WP.xgmml")
hsa_react <- file.path(getwd(), "Linksets", "wikipathways-20220511-hsa-REACTOME.xgmml")
  #Loading the WikiPathways linksets available at https://cytargetlinker.github.io/pages/linksets/wikipathways
CTLextend.cmd = paste('cytargetlinker extend idAttribute="XrefId" linkSetFiles="', hsa, ',', hsa_react, '" network=current direction=TARGETS', sep="")
commandsRun(CTLextend.cmd)
  #Extending the network with previously loaded linksets
layoutNetwork()
  #Adding basic network layout
snw_adc_ext <- getNetworkName()

## STRINGIFY ---------------------------------------------------------------------------------------------------------------------------
setCurrentNetwork(snw_adc)
commandsRun("string stringify column=name compoundQuery=false cutoff=0.4 includeNotMapped=false networkNoGui=current networkType='full STRING network' species='Homo sapiens'")
## PharmGKB ----------------------------------------------------------------------------------------------------------------------------
pgkb.import <- function(pgkb_id,pgkb_name) {
  pgkburl = sprintf("https://api.pharmgkb.org/v1/download/pathway/%s?format=.tsv", pgkb_id)
  pgkb_name <- paste0(pgkb_name,".tsv")
  download.file(pgkburl, sprintf("PharmGKB pathways/%s",pgkb_name))
  commandsRun(sprintf("network import file indexColumnSourceInteraction=From indexColumnTargetInteraction=To file=PharmGKB pathways/%s",pgkb_name))
}
pgkb.import("PA166170742","Antipsychotics pathway")
## SAVING ------------------------------------------------------------------------------------------------------------------------------

preserve <- c(snw_scz, snw_scz_ext,snw_adc,snw_adc_ext)

# WIP ==================================================================================================================================


## INTERSECTION -----------------------------------------------------------------------------------------------------------------------

scz_pathways.names <- paste(scz_pathways$name, scz_pathways$species, sep = " - ")
adc_pathways.names <- paste(adc_pathways$name, adc_pathways$species, sep = " - ")
  #Getting the names of the pathways as shown in Cytoscape, which includes the species 

intersect_df <- expand.grid(scz_pathways.names, adc_pathways.names)
intersect_df <- as.data.frame(lapply(intersect_df, as.character))
  #Matching every SCZ pathway against every addiction pathway to detect all interactions and forcing entries to be characters (required for mergeNetwork)
intersect <- function(row) {
  col1 <- row[1]
  col2 <- row[2]
  mergeNetworks(c(col1,col2),(paste(col1,col2, sep =  " - ")),"intersection")
  getIntersections <- as.character(getAllNodes())
  #Getting the nodes resulting in the intersection networks
  list(intersection_names = paste(getIntersections,collapse = ", "))
  #Extracting the names of these nodes and making them more legible
    #Merging networks with 'intersect' parameter
}
df_results <- apply(intersect_df,1,intersect)
intersection_names <- sapply(df_results, function(x) x$intersection_names)
intersect_df$intersection_names <- intersection_names
  #Adding the intersections to a new column in the df 
intersect_df <- intersect_df %>% mutate_all(~na_if(.,""))
  #Some pathways do not have any overlaps, so the field in the df is marked as NA
intersect_df <- cbind(intersect_df, scz_pathways.ids, adc_pathways.ids)
intersect_df <- intersect_df %>%
  select (scz_pathways.ids,Var1, adc_pathways.ids,Var2,intersection_names)
names(intersect_df) <- c("SCZ WP ID","SCZ pathway","ADC WP ID","Addiction pathway", "Intersections")
  #Reordering and renaming the df columns for easier reading

View(intersect_df)
write.csv(intersect_df, file = "CSVs/Intersections.csv")






